/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ninjav.conan.ui.dashboard;

import org.ninjav.conan.account.PresentableFinancials;

/**
 *
 * @author ninjav
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financialsSummaryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalFundsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        owedFundsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paidFundsLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        recoveredFundsLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        writtenOffFundsLabel = new javax.swing.JLabel();
        accountsSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberOfAccountsLabel = new javax.swing.JLabel();
        numberOfAccountsInArrearsLabel = new javax.swing.JLabel();
        debitOrdersSummary = new javax.swing.JPanel();
        totalPaidDebitOrdersLabel = new javax.swing.JLabel();
        totalDebitOrdersLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalUnpaidDebitOrdersLabel = new javax.swing.JLabel();

        financialsSummaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Financials Summary"));

        jLabel1.setText("Total Funds:");

        totalFundsLabel.setText("0.00");

        jLabel2.setText("Owed Funds:");

        owedFundsLabel.setText("0.00");

        jLabel3.setText("Paid Funds:");

        paidFundsLabel.setText("0.00");

        jLabel9.setText("Recovered:");

        recoveredFundsLabel.setText("0.00");

        jLabel10.setText("Written off:");

        writtenOffFundsLabel.setText("0.00");

        javax.swing.GroupLayout financialsSummaryPanelLayout = new javax.swing.GroupLayout(financialsSummaryPanel);
        financialsSummaryPanel.setLayout(financialsSummaryPanelLayout);
        financialsSummaryPanelLayout.setHorizontalGroup(
            financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financialsSummaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(financialsSummaryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paidFundsLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financialsSummaryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(owedFundsLabel))
                    .addGroup(financialsSummaryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(133, 133, 133)
                        .addComponent(totalFundsLabel)))
                .addGap(18, 18, 18)
                .addGroup(financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recoveredFundsLabel)
                    .addComponent(writtenOffFundsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        financialsSummaryPanelLayout.setVerticalGroup(
            financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financialsSummaryPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalFundsLabel)
                    .addComponent(jLabel10)
                    .addComponent(writtenOffFundsLabel))
                .addGap(18, 18, 18)
                .addGroup(financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(owedFundsLabel)
                    .addComponent(jLabel9)
                    .addComponent(recoveredFundsLabel))
                .addGap(18, 18, 18)
                .addGroup(financialsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paidFundsLabel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        accountsSummaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Accounts Summary"));

        jLabel5.setText("Number of Accounts in Arrears:");

        jLabel4.setText("Number of Accounts:");

        numberOfAccountsLabel.setText("0");

        numberOfAccountsInArrearsLabel.setText("0");

        javax.swing.GroupLayout accountsSummaryPanelLayout = new javax.swing.GroupLayout(accountsSummaryPanel);
        accountsSummaryPanel.setLayout(accountsSummaryPanelLayout);
        accountsSummaryPanelLayout.setHorizontalGroup(
            accountsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsSummaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(accountsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfAccountsLabel)
                    .addComponent(numberOfAccountsInArrearsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountsSummaryPanelLayout.setVerticalGroup(
            accountsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsSummaryPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(accountsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberOfAccountsLabel))
                .addGap(18, 18, 18)
                .addGroup(accountsSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numberOfAccountsInArrearsLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        debitOrdersSummary.setBorder(javax.swing.BorderFactory.createTitledBorder("Debit Orders Summary"));

        totalPaidDebitOrdersLabel.setText("0");

        totalDebitOrdersLabel.setText("0");

        jLabel6.setText("Total Debit Orders:");

        jLabel7.setText("Total Paid Debit Orders:");

        jLabel8.setText("Total Unpaid Debit Orders:");

        totalUnpaidDebitOrdersLabel.setText("0");

        javax.swing.GroupLayout debitOrdersSummaryLayout = new javax.swing.GroupLayout(debitOrdersSummary);
        debitOrdersSummary.setLayout(debitOrdersSummaryLayout);
        debitOrdersSummaryLayout.setHorizontalGroup(
            debitOrdersSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitOrdersSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(debitOrdersSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(48, 48, 48)
                .addGroup(debitOrdersSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPaidDebitOrdersLabel)
                    .addComponent(totalUnpaidDebitOrdersLabel)
                    .addComponent(totalDebitOrdersLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        debitOrdersSummaryLayout.setVerticalGroup(
            debitOrdersSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debitOrdersSummaryLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(debitOrdersSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalDebitOrdersLabel))
                .addGap(18, 18, 18)
                .addGroup(debitOrdersSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalPaidDebitOrdersLabel))
                .addGap(18, 18, 18)
                .addGroup(debitOrdersSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalUnpaidDebitOrdersLabel))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(financialsSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountsSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(debitOrdersSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 696, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(financialsSummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountsSummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(debitOrdersSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountsSummaryPanel;
    private javax.swing.JPanel debitOrdersSummary;
    private javax.swing.JPanel financialsSummaryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel numberOfAccountsInArrearsLabel;
    private javax.swing.JLabel numberOfAccountsLabel;
    private javax.swing.JLabel owedFundsLabel;
    private javax.swing.JLabel paidFundsLabel;
    private javax.swing.JLabel recoveredFundsLabel;
    private javax.swing.JLabel totalDebitOrdersLabel;
    private javax.swing.JLabel totalFundsLabel;
    private javax.swing.JLabel totalPaidDebitOrdersLabel;
    private javax.swing.JLabel totalUnpaidDebitOrdersLabel;
    private javax.swing.JLabel writtenOffFundsLabel;
    // End of variables declaration//GEN-END:variables

    public void reset() {
        numberOfAccountsInArrearsLabel.setText("0");
        numberOfAccountsLabel.setText("0");
        owedFundsLabel.setText("0.00");
        paidFundsLabel.setText("0.00");
        writtenOffFundsLabel.setText("0.00");
        recoveredFundsLabel.setText("0.00");
        totalDebitOrdersLabel.setText("0");
        totalFundsLabel.setText("0.00");
        totalPaidDebitOrdersLabel.setText("0");
        totalUnpaidDebitOrdersLabel.setText("0");
    }

    public void presentFinancials(PresentableFinancials financials) {
        numberOfAccountsInArrearsLabel.setText(Long.toString(financials.numberOfAccountsInArrears));
        numberOfAccountsLabel.setText(Long.toString(financials.numberOfAccounts));
        owedFundsLabel.setText(formatAmount(financials.owedFunds));
        paidFundsLabel.setText(formatAmount(financials.paidFunds));
        writtenOffFundsLabel.setText(formatAmount(financials.writtenOffFunds));
        recoveredFundsLabel.setText(formatAmount(financials.recoveredFunds));
        totalDebitOrdersLabel.setText(Long.toString(financials.totalDebitOrders));
        totalFundsLabel.setText(formatAmount(financials.totalFunds));
        totalPaidDebitOrdersLabel.setText(Long.toString(financials.totalPaidDebitOrders));
        totalUnpaidDebitOrdersLabel.setText(Long.toString(financials.totalUnpaidDebitOrders));
    }

    private String formatAmount(double owedFunds) {
        return String.format("%.2f", owedFunds);
    }
}
