/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ninjav.conan.ui;

import org.ninjav.conan.ui.account.AccountPanel;
import org.ninjav.conan.ui.core.MainPanel;
import org.ninjav.conan.ui.logger.LoggerPanel;
import org.ninjav.conan.ui.reconciler.ReconcilePanel;
import org.ninjav.conan.ui.statement.StatementPanel;

/**
 *
 * @author ninjav
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MainPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public MainPanel getMainPanel() {
        return mainPanel;
    }

    public ReconcilePanel getReconcilePanel() {
        return mainPanel.getReconcilePanel();
    }
    
    public LoggerPanel getLoggerPanel() {
        return mainPanel.getLoggerPanel();
    }

    public StatementPanel getStatementPanel() {
        return mainPanel.getStatementPanel();
    }
    
    public AccountPanel getAccountPanel() {
        return mainPanel.getAccountPanel();
    }
}
