/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ninjav.conan.ui.core;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author ninjav
 */
public class UserPanel extends javax.swing.JPanel {
    public static final String LOGIN_VIEW = "loginPane";
    public static final String LOGOUT_VIEW = "logoutPane";
    
    private final String DEFAULT_PASSWORD = "password";
    private final String DEFAULT_USERNAME = "username";
    
    /**
     * Creates new form UserForm
     */
    public UserPanel() {
        initComponents();
        reset();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPane = new javax.swing.JPanel();
        signInButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        userNameField = new javax.swing.JTextField();
        logoutPane = new javax.swing.JPanel();
        signOutButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        loginPane.setBackground(new java.awt.Color(255, 255, 255));
        loginPane.setName("loginPane"); // NOI18N

        signInButton.setText("Sign-in");

        passwordField.setText("Password...");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });

        userNameField.setText("Username...");
        userNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout loginPaneLayout = new javax.swing.GroupLayout(loginPane);
        loginPane.setLayout(loginPaneLayout);
        loginPaneLayout.setHorizontalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signInButton)
                .addContainerGap())
        );
        loginPaneLayout.setVerticalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInButton)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(loginPane, "loginPane");

        logoutPane.setBackground(new java.awt.Color(255, 255, 255));
        logoutPane.setName("logoutPane"); // NOI18N

        signOutButton.setText("Sign-off");

        javax.swing.GroupLayout logoutPaneLayout = new javax.swing.GroupLayout(logoutPane);
        logoutPane.setLayout(logoutPaneLayout);
        logoutPaneLayout.setHorizontalGroup(
            logoutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPaneLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(signOutButton)
                .addContainerGap())
        );
        logoutPaneLayout.setVerticalGroup(
            logoutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(logoutPane, "logoutPane");
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusGained
        if (userNameField.getText().equals(DEFAULT_USERNAME)) {
            selectAll(userNameField);
        }
    }//GEN-LAST:event_userNameFieldFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (new String(passwordField.getPassword()).equals(DEFAULT_PASSWORD)) {
            selectAll(passwordField);
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void selectAll(JTextField field) {
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel loginPane;
    private javax.swing.JPanel logoutPane;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    public void showView(String viewName) {
        CardLayout cards = (CardLayout)getLayout();
        cards.show(this, viewName);
    }
    
    public String getUserName() {
        return userNameField.getText().trim();
    }
    
    public String getPassword() {
        return new String(passwordField.getPassword());
    }
    
    public void reset() {
        userNameField.setText(DEFAULT_USERNAME);
        passwordField.setText(DEFAULT_PASSWORD);
    }
    
    public JButton getSignInButton() {
        return signInButton;
    }
    
    public JButton getSignOutButton() {
        return signOutButton;
    }
    
    public JTextField getPasswordField() {
        return passwordField;
    }
}

