/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ninjav.conan.ui.reconciler;

import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author ninjav
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reconcileButton = new javax.swing.JButton();
        notesScroller = new javax.swing.JScrollPane();
        notesField = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chronologicalLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        selectedDebitsLabel = new javax.swing.JLabel();
        selectedCreditsLabel = new javax.swing.JLabel();

        reconcileButton.setText("Reconcile");

        notesField.setColumns(20);
        notesField.setRows(5);
        notesScroller.setViewportView(notesField);

        jLabel9.setText("Note:");

        jLabel8.setText("Transactions chronological:");

        jLabel7.setText("Balance:");

        jLabel6.setText("Selected debits total:");

        jLabel5.setText("Selected credits total:");

        chronologicalLabel.setText("-");

        balanceLabel.setText("0");

        selectedDebitsLabel.setText("0");

        selectedCreditsLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedCreditsLabel)
                            .addComponent(selectedDebitsLabel)
                            .addComponent(balanceLabel)
                            .addComponent(chronologicalLabel)))
                    .addComponent(notesScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reconcileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(selectedCreditsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(selectedDebitsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(balanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chronologicalLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesScroller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reconcileButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel chronologicalLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea notesField;
    private javax.swing.JScrollPane notesScroller;
    private javax.swing.JButton reconcileButton;
    private javax.swing.JLabel selectedCreditsLabel;
    private javax.swing.JLabel selectedDebitsLabel;
    // End of variables declaration//GEN-END:variables

    public void updateCreditsLabel(String amount) {
        selectedCreditsLabel.setText(amount);
    }
    
    public void updateDebitsLabel(String amount) {
        selectedDebitsLabel.setText(amount);
    }
    
    public void updateBalanceLabel(String amount) {
        balanceLabel.setText(amount);
    }
    
    public void updateChronologicalLabel(String text) {
        chronologicalLabel.setText(text);
    }
        
    public void reset() {
        selectedCreditsLabel.setText("-");
        selectedDebitsLabel.setText("-");
        balanceLabel.setText("-");
        chronologicalLabel.setText("-");
        notesField.setText("");
        reconcileButton.setEnabled(false);
    }

    public JButton getReconcileButton() {
        return reconcileButton;
    }

    public JTextArea getNotesField() {
        return notesField;
    }
}
